import type { Metadata } from "next";
import { Button, Card, Input, Label } from "@/components/ui";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Login Page generated by create next app",
};

function LoginPage() {
  return <div>LoginPage</div>;
}
export default LoginPage;
