import type { Metadata } from "next";
import { Button, Card, Input, Label } from "@/components/ui";


export const metadata: Metadata = {
  title: "Register Page",
  description: "Register Page generated by create next app",
};


function RegisterPage() {
  return (
    <div>
      <h1>Register</h1>

      <Button>Boton</Button>
      <Button>Boton</Button>
      <Button>Boton</Button>
      <Button>Boton</Button>
    </div>
  );
}
export default RegisterPage;
