import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import { Button, Card, Input, Label } from "@/components/ui";


export const metadata: Metadata = {
  title: "About Page",
  description: "About Page generated by create next app",
};

function AboutPage() {
  return (
    <section>
    <Navbar />
      <div>
        aboutPage
      </div>
    </section>
  );
}
export default AboutPage;
