import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard Page",
  description: "Dashboard Page generated by create next app",
};


function DashboadPage() {
  return (
    <div>
      DashboadPage
    </div>
  )
}
export default DashboadPage